#!/usr/bin/env bash
# Regenerates crates/mb-formats/src/dequant_golden.rs from PrismML's reference
# quantizer/dequantizer, extracted verbatim from a PrismML-Eng/llama.cpp checkout.
#
#   git clone --depth 1 https://github.com/PrismML-Eng/llama.cpp /tmp/prism-llama.cpp
#   scripts/prism-golden.sh /tmp/prism-llama.cpp
set -euo pipefail
FORK=${1:?usage: $0 <PrismML-Eng/llama.cpp checkout>}
Q="$FORK/ggml/src/ggml-quants.c"
OUT="$(cd "$(dirname "$0")/.." && pwd)/crates/mb-formats/src/dequant_golden.rs"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
{
cat <<'C'
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <assert.h>
#include <string.h>
#define GGML_RESTRICT
#define MAX(a,b) ((a)>(b)?(a):(b))
typedef uint16_t ggml_half;
static float h2f(ggml_half h){ _Float16 f; memcpy(&f,&h,2); return (float)f; }
static ggml_half f2h(float x){ _Float16 f=(_Float16)x; ggml_half h; memcpy(&h,&f,2); return h; }
#define GGML_FP16_TO_FP32 h2f
#define GGML_FP32_TO_FP16 f2h
C
sed -n '/^#define QK_PQ2_0 128/,/wrong ptq1_0 block/p' "$FORK/ggml/src/ggml-common.h"
sed -n '/^void quantize_row_pq2_0_ref/,/^}/p' "$Q"
sed -n '/^void dequantize_row_pq2_0/,/^}/p' "$Q"
sed -n '/^static const size_t ptq1_0_stages/p' "$Q"
sed -n '/^void quantize_row_ptq1_0_ref/,/^}/p' "$Q"
sed -n '/^void dequantize_row_ptq1_0/,/^}/p' "$Q"
cat <<'C'
static uint32_t rs=12345; static int trit(void){ rs=rs*1103515245u+12345u; return (int)((rs>>16)%3)-1; }
static void hex(const char*name,const void*p,size_t n){ const uint8_t*b=p; printf("%s ",name); for(size_t i=0;i<n;i++) printf("%02x",b[i]); printf("\n"); }
int main(void){
  enum{NB=2,K=NB*128}; float x[K], y[K]; float scales[NB]={0.0123f,0.5f};
  for(int i=0;i<K;i++) x[i]=trit()*scales[i/128];
  block_pq2_0 p[NB]; quantize_row_pq2_0_ref(x,p,K); dequantize_row_pq2_0(p,y,K);
  for(int i=0;i<K;i++) assert(fabsf(y[i]-x[i])<1e-3f*scales[i/128]+1e-6f);
  hex("pq2_0",p,sizeof p);
  block_ptq1_0 t[NB]; quantize_row_ptq1_0_ref(x,t,K); dequantize_row_ptq1_0(t,y,K);
  for(int i=0;i<K;i++) assert(fabsf(y[i]-x[i])<1e-3f*scales[i/128]+1e-6f);
  hex("ptq1_0",t,sizeof t);
  printf("codes "); for(int i=0;i<K;i++) printf("%d,", (int)lroundf(x[i]/scales[i/128])); printf("\n");
  printf("scales_f16 "); for(int i=0;i<NB;i++) printf("%.9g,", h2f(f2h(scales[i]))); printf("\n");
  return 0;
}
C
} > "$WORK/harness.c"
cc -O1 -std=c11 -o "$WORK/harness" "$WORK/harness.c" -lm
"$WORK/harness" > "$WORK/golden.txt"   # asserts the reference round-trips
COMMIT="$(git -C "$FORK" rev-parse --short HEAD 2>/dev/null || echo unknown)"
field() { awk -v k="$1" '$1==k {print $2}' "$WORK/golden.txt" | sed 's/,$//'; }
cat > "$OUT" <<RS
// Generated by scripts/prism-golden.sh from PrismML-Eng/llama.cpp @ $COMMIT
// (quantize_row_*_ref + dequantize_row_*, extracted verbatim). Do not edit.
pub const PQ2_0_HEX: &str = "$(field pq2_0)";
pub const PTQ1_0_HEX: &str = "$(field ptq1_0)";
pub const CODES: [i8; 256] = [$(field codes)];
pub const SCALES: [f32; 2] = [$(field scales_f16)];
RS
echo "wrote $OUT"
